### ISSUE TITLE
Failed to compile warehouse_ros under Jade / Trusty

### ISSUE THREAD

**Issue by cschindlbeck** [ros-planning/warehouse_ros#29]
I am having problems running MoveIt under ROS Jade / Ubuntu Trusty lately, mongoDB seem to be the problem.
Here is the specific compile error:

```
Linking CXX executable /home/chris/catkin_ws/devel/lib/warehouse_ros/test_mongo_roscpp
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libmongoclient.a(gridfs.o): undefined reference to symbol '_ZN5boost10filesystem6detail6statusERKNS0_4pathEPNS_6system10error_codeE'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_filesystem.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [/home/chris/catkin_ws/devel/lib/warehouse_ros/test_mongo_roscpp] Error 1
make[1]: *** [warehouse_ros/CMakeFiles/test_mongo_roscpp.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j1 -l1" failed
```

Any solutions?

**Comment by cschindlbeck** [comment]
Seems to work with 
git clone -b jade_devel https://github.com/TheBrewCrew/warehouse_ros_mongo.git

**Comment by cschindlbeck** [comment]
Now rViz crashes on 
roslaunch moveit_config demo.setup 

Can someone help me out what is the best approach to solve this?

**Comment by 130s** [comment]
Now that #32 is merged, which works around a long-lasting mongo issue for Jade (#22), the error you're seeing is likely not occurring any more. Please try `jade-devel` branch for Jade, and don't hesitate to reopen if the issue still persists.
