### ISSUE TITLE
rename master to indigo-devel?

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/warehouse_ros#33]
@davetcoleman -- it appears this should happen? If there are no objections I will do this later tonight during release of jade/kinetic

**Comment by davetcoleman** [comment]
shouldn't it be jade or kinetic -devel? are these changes also being released in indigo?

**Comment by mikeferguson** [comment]
We have a jade-devel branch -- which is where the commits earlier today were targeted. From what I see, jade-devel is currently 12 commits ahead of master, 2 behinds (the two commits are adding trusty-based CI config and you merging that config). Thus, I think master should be named indigo-devel and the default branch should be switched to jade-devel, I just wanted to make sure I wasn't missing anything

**Comment by davetcoleman** [comment]
+1

**Comment by 130s** [comment]
+1

I just checked out master as `indigo-devel` and pushed it to remote. If anyone could switch default then I can remove `master` from remote.

**Comment by mikeferguson** [comment]
Default switched, master removed. Thanks!

**Comment by mikeferguson** [comment]
Updated branch names in gbp: https://github.com/ros-gbp/warehouse_ros-release/commit/d05b1f533f04506f0f384622d17d09518b3e00c1

**Comment by mikeferguson** [comment]
I'm going to wait fro the branch name update to be merged into rosdistro before doing a release on this into j+k

**Comment by 130s** [comment]
I think branch is updated and we're ready to make a release. Can I make releases?

**Comment by mikeferguson** [comment]
@130s -- go right ahead -- we shouldn't do anything with Indigo, but release J+K from the jade-devel (with a minor bump, so 0.9.0)

**Comment by 130s** [comment]
@mikeferguson I got it. Now running prerelease test locally for Jade.

**Comment by davetcoleman** [comment]
great! :octocat:

**Comment by 130s** [comment]
Local prerelease test looked good. Now they are release-requested, fingers crossed.
J https://github.com/ros/rosdistro/pull/11897, K https://github.com/ros/rosdistro/pull/11898
