### ISSUE TITLE
mongo_ros dependency

### ISSUE THREAD

**Issue by acesso** [ros-planning/warehouse_ros#34]
The indigo-devel branch requires the mongo_ros package which is deprecated since groovy, the source of mongo_ros is already unavailable for quite long time. 

related to this I've PR at moveit_ros (indigo-devel) at https://github.com/ros-planning/moveit_ros/pull/720 which uses warehouse_ros for jade-devel, not sure if this should be update here or at the moveit_ros repo.

**Comment by davetcoleman** [comment]
i believe @mikeferguson understands this history of mongo much better than I

**Comment by mikeferguson** [comment]
AFAIK, warehouse_ros depends on mongo, but not mongo_ros.

The issue we were fixing in Jade+ is that the mongo_db packaging has changed in recent versions. Historically, mongo included the C++ client in the server source, so it was packaged alongside the server. With recent versions, the C++ client has been removed from the server, and thus has to be released separately. Recent versions of Ubuntu (15.04+) fail to package the C++ client at all, which led to our refactor to make warehouse_ros plugin-based and agnostic to the database. At the moment however, we have implemented exactly 0 plugins -- so we have effectively rendered the benchmarks and scene storage inert in Jade+ until someone implements and releases a database plugin.

**Comment by v4hn** [comment]
Closing as invalid.
See https://github.com/ros-planning/moveit_ros/pull/720#issuecomment-233706106 for more information.

@mikeferguson: Now that is a pretty lousy way to "fix" the mongo client issue.  :/
I suppose a new mongodb plugin should be implemented rather soon.
The mongo c client library has been around for quite a while now and it's [part of xenial](http://packages.ubuntu.com/xenial/libmongoc-dev), so with moving to kinetic, a mongo client plugin becomes feasible.
However, as currently none of the maintainers is actually _using_ the warehouse, we'll see how this goes...
