### ISSUE TITLE
Release into ROS Lunar

### ISSUE THREAD

**Issue by 130s** [ros-planning/warehouse_ros#36]
Apparently this blocks the release of [some packages](http://repositories.ros.org/status_page/blocked_releases_lunar.html?s=6&r=1).

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/14531

Can **any admin of this repo** help to enable the pull request testing by only a few clicks? Please follow [this instruction](http://wiki.ros.org/buildfarm/Pull%20request%20testing#Link_Jenkins_and_your_.21GitHub_repository) ("Recommended" section).

Other chores is already taken care of. Once it's done, then pull request testing powered-by ROS buildfarm will become available.

**Comment by 130s** [comment]
> Can **any admin of this repo** help to enable the pull request testing by only a few clicks? Please follow [this instruction](http://wiki.ros.org/buildfarm/Pull%20request%20testing#Link_Jenkins_and_your_.21GitHub_repository) ("Recommended" section).

@dirk-thomas do you have a spare cycle for this?

**Comment by dirk-thomas** [comment]
Please see https://github.com/ros/rosdistro/pull/14530#discussion_r111661080 I already added the ROS buildfarm user to the `ros-planning` org unit.
