### ISSUE TITLE
Example code missing

### ISSUE THREAD

**Issue by krixkrix** [ros-planning/warehouse_ros#42]
The link in the wiki is dead and no files seems to exist that shows an example.
The file mongo_ros.test refers to some testing code, but the files are not to be found.

**Comment by rhaschke** [comment]
Indeed `mongo_ros.test` is dead and not used for testing (anymore).
However, looking into the src folder, I immediately found [`test_dbloader.cpp`](https://github.com/ros-planning/warehouse_ros/blob/fa580c7f30d4a34a07d97c228f56000352145354/src/test_dbloader.cpp).
It would have been helpful, if you would have refered to the "dead link in the wiki". 
Looks like #32 removed a whole bunch of unit tests, including the [example referenced in the wiki](http://wiki.ros.org/warehouse_ros/Tutorials/Using%20the%20C%2B%2B%20client%20library).

**Comment by rhaschke** [comment]
I removed the obsolete `mongo_ros.test` file. Anybody updating the wiki is highly welcome.

**Comment by 130s** [comment]
I just [fixed a wiki (wiki.ros.org)](http://wiki.ros.org/action/info/warehouse_ros/Tutorials/Running%20the%20warehouse?action=diff&rev2=3&rev1=2) page with an outdated info.

That said I share the sentiment that the operational info is missing. I hope to find:
- How to execute the tool.
- What type of data can/not be stored.
   - Not even sure if rostopic messages (which can be stored by other tools e.g. `rosbag`), changes in dynamic_reconfigure/ROS parameter servers can be stored. If not, is there a way to link the timestamp?
- Which channel can/not be stored (e.g. Does it only capture the data through ROS Master?).
- Output data format example.

**Comment by rhaschke** [comment]
Thanks Isaac for fixing the wiki. I will close this issue now.
