### ISSUE TITLE
Release warehouse_ros into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-planning/warehouse_ros#46]
Would you mind releasing `warehouse_ros` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 41 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by rhaschke** [comment]
Triggered new releases into [Kinetic](https://github.com/ros/rosdistro/pull/24584), [Melodic](https://github.com/ros/rosdistro/pull/24585) and [Noetic](https://github.com/ros/rosdistro/pull/24586).
