### ISSUE TITLE
[ROS2] New Release for All Distributions

### ISSUE THREAD

**Issue by vatanaksoytezer** [ros-planning/warehouse_ros#81]
To have a successful moveit2 release without SSL errors (see https://github.com/ros-planning/moveit2/pull/514 for details.) we need #80. To avoid buildfarm failures when we release moveit2, we would require a new release  of `warehouse_ros` on all three distributions that we support (Foxy, Galactic and Rolling).

**Comment by henningkayser** [comment]
done https://github.com/ros-planning/warehouse_ros/pull/84
