### ISSUE TITLE
Add constructor to database loader which takes a NodeParametersInterface

### ISSUE THREAD

**Issue by calenr** [ros-planning/warehouse_ros#96]
Currently the database loader can only be used with in conjunction with a `Node::SharedPtr`. In order to make it compatible with lifecycle nodes (or any object which stores a `NodeParameterInterface`) the `DatabaseLoader` could be modified to store a `NodeParameterInterface` instead of a `Node`. This would require a new constructor which takes in a new `NodeParameterInterface`, and the current constructor (which accepts a shared pointer to a node) would delegate to this new constructor.

**Comment by rhaschke** [comment]
Addressed via #97.
